on: push
name: Code Quality
jobs:
  testing:
    name: Checking the code
    runs-on: ubuntu-latest
    container: node:12.10.0-buster-slim
    steps:
      - uses: actions/checkout@master
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
